= Definitions
:navtitle: Definitions

== Based on definitions from IEEE

https://pascal.computer.org/[SEVOCAB]
https://zbib.org/[Bibliography Search]

Context::
* immediate environment in which a function (or set of functions in a diagram) operates

Module::
* program unit that is discrete and identifiable with respect to compiling, combining with other units, and loading (ISO/IEC 19506)

Component vs module::

Faults vs failures::

analysis vs analytics::
* analysis - examine the historical data, understand present and assess the gap or differences between them, includes listing and prioritizing the specific actions or tasks required to close the gap.
* analytics - try to predict future for decision making

Modeling::
* referring to mathematics equation or plot diagram. e.g. f(x) = 1/x

Simulation::
* referring to executable runtime program, e.g. kotlin app.

Role vs Responsibility::
* Role and responsibility are two interconnected concepts that define a person's position and obligations within a particular context

Responsibility vs Accountability::
* Responsibility is task-oriented, while accountability is outcome-oriented.


competency vs skill (based on ACM)::
* competency - know-what = a.k.a knowledge area (K.A)
* skill - know-how disposition - know-why


programming vs engineering::

design vs architecture::

requirement vs need::

quality assurance vs testing::


solution vs implementation::

POC vs MVP vs MMP::
* MVP is problem solution fit but not yet product market fit
* MMP is product market fit with revenue and profit

rationalism vs empiricism (brooks)::

reward::
* incentive
* reward
* recognition

== Convention

Date Format::
explicitly state the month and day using words rather than just numerals (e.g. "October 31, 2023" or Oct 31, 2023 --less formal).
commonly put year after month, in english.
put time after date, so remember "dateYeartime" DayTime Monday, June 22, 2023, 9:30 AM